/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedValuationsIndexRouteImport } from './routes/_authenticated/valuations/index'
import { Route as AuthenticatedValuationEstimatesIndexRouteImport } from './routes/_authenticated/valuation-estimates/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedInstitutionsIndexRouteImport } from './routes/_authenticated/institutions/index'
import { Route as AuthenticatedInstitutionTypesIndexRouteImport } from './routes/_authenticated/institution-types/index'
import { Route as AuthenticatedBranchesIndexRouteImport } from './routes/_authenticated/branches/index'
import { Route as AuthenticatedValuationsNewRouteImport } from './routes/_authenticated/valuations/new'
import { Route as AuthenticatedValuationsIdRouteImport } from './routes/_authenticated/valuations/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedValuationsIndexRoute =
  AuthenticatedValuationsIndexRouteImport.update({
    id: '/valuations/',
    path: '/valuations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedValuationEstimatesIndexRoute =
  AuthenticatedValuationEstimatesIndexRouteImport.update({
    id: '/valuation-estimates/',
    path: '/valuation-estimates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstitutionsIndexRoute =
  AuthenticatedInstitutionsIndexRouteImport.update({
    id: '/institutions/',
    path: '/institutions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstitutionTypesIndexRoute =
  AuthenticatedInstitutionTypesIndexRouteImport.update({
    id: '/institution-types/',
    path: '/institution-types/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBranchesIndexRoute =
  AuthenticatedBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedValuationsNewRoute =
  AuthenticatedValuationsNewRouteImport.update({
    id: '/valuations/new',
    path: '/valuations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedValuationsIdRoute =
  AuthenticatedValuationsIdRouteImport.update({
    id: '/valuations/$id',
    path: '/valuations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/valuations/$id': typeof AuthenticatedValuationsIdRoute
  '/valuations/new': typeof AuthenticatedValuationsNewRoute
  '/branches': typeof AuthenticatedBranchesIndexRoute
  '/institution-types': typeof AuthenticatedInstitutionTypesIndexRoute
  '/institutions': typeof AuthenticatedInstitutionsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/valuation-estimates': typeof AuthenticatedValuationEstimatesIndexRoute
  '/valuations': typeof AuthenticatedValuationsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/valuations/$id': typeof AuthenticatedValuationsIdRoute
  '/valuations/new': typeof AuthenticatedValuationsNewRoute
  '/branches': typeof AuthenticatedBranchesIndexRoute
  '/institution-types': typeof AuthenticatedInstitutionTypesIndexRoute
  '/institutions': typeof AuthenticatedInstitutionsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/valuation-estimates': typeof AuthenticatedValuationEstimatesIndexRoute
  '/valuations': typeof AuthenticatedValuationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/valuations/$id': typeof AuthenticatedValuationsIdRoute
  '/_authenticated/valuations/new': typeof AuthenticatedValuationsNewRoute
  '/_authenticated/branches/': typeof AuthenticatedBranchesIndexRoute
  '/_authenticated/institution-types/': typeof AuthenticatedInstitutionTypesIndexRoute
  '/_authenticated/institutions/': typeof AuthenticatedInstitutionsIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/valuation-estimates/': typeof AuthenticatedValuationEstimatesIndexRoute
  '/_authenticated/valuations/': typeof AuthenticatedValuationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/valuations/$id'
    | '/valuations/new'
    | '/branches'
    | '/institution-types'
    | '/institutions'
    | '/roles'
    | '/users'
    | '/valuation-estimates'
    | '/valuations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/valuations/$id'
    | '/valuations/new'
    | '/branches'
    | '/institution-types'
    | '/institutions'
    | '/roles'
    | '/users'
    | '/valuation-estimates'
    | '/valuations'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/valuations/$id'
    | '/_authenticated/valuations/new'
    | '/_authenticated/branches/'
    | '/_authenticated/institution-types/'
    | '/_authenticated/institutions/'
    | '/_authenticated/roles/'
    | '/_authenticated/users/'
    | '/_authenticated/valuation-estimates/'
    | '/_authenticated/valuations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/valuations/': {
      id: '/_authenticated/valuations/'
      path: '/valuations'
      fullPath: '/valuations'
      preLoaderRoute: typeof AuthenticatedValuationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/valuation-estimates/': {
      id: '/_authenticated/valuation-estimates/'
      path: '/valuation-estimates'
      fullPath: '/valuation-estimates'
      preLoaderRoute: typeof AuthenticatedValuationEstimatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institutions/': {
      id: '/_authenticated/institutions/'
      path: '/institutions'
      fullPath: '/institutions'
      preLoaderRoute: typeof AuthenticatedInstitutionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/institution-types/': {
      id: '/_authenticated/institution-types/'
      path: '/institution-types'
      fullPath: '/institution-types'
      preLoaderRoute: typeof AuthenticatedInstitutionTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches/': {
      id: '/_authenticated/branches/'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/valuations/new': {
      id: '/_authenticated/valuations/new'
      path: '/valuations/new'
      fullPath: '/valuations/new'
      preLoaderRoute: typeof AuthenticatedValuationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/valuations/$id': {
      id: '/_authenticated/valuations/$id'
      path: '/valuations/$id'
      fullPath: '/valuations/$id'
      preLoaderRoute: typeof AuthenticatedValuationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedValuationsIdRoute: typeof AuthenticatedValuationsIdRoute
  AuthenticatedValuationsNewRoute: typeof AuthenticatedValuationsNewRoute
  AuthenticatedBranchesIndexRoute: typeof AuthenticatedBranchesIndexRoute
  AuthenticatedInstitutionTypesIndexRoute: typeof AuthenticatedInstitutionTypesIndexRoute
  AuthenticatedInstitutionsIndexRoute: typeof AuthenticatedInstitutionsIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedValuationEstimatesIndexRoute: typeof AuthenticatedValuationEstimatesIndexRoute
  AuthenticatedValuationsIndexRoute: typeof AuthenticatedValuationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedValuationsIdRoute: AuthenticatedValuationsIdRoute,
  AuthenticatedValuationsNewRoute: AuthenticatedValuationsNewRoute,
  AuthenticatedBranchesIndexRoute: AuthenticatedBranchesIndexRoute,
  AuthenticatedInstitutionTypesIndexRoute:
    AuthenticatedInstitutionTypesIndexRoute,
  AuthenticatedInstitutionsIndexRoute: AuthenticatedInstitutionsIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedValuationEstimatesIndexRoute:
    AuthenticatedValuationEstimatesIndexRoute,
  AuthenticatedValuationsIndexRoute: AuthenticatedValuationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
