/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedValuationEstimatesIndexRouteImport } from './routes/_authenticated/valuation-estimates/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedCasesIndexRouteImport } from './routes/_authenticated/cases/index'
import { Route as AuthenticatedCasesNewRouteImport } from './routes/_authenticated/cases/new'
import { Route as AuthenticatedCasesIdRouteImport } from './routes/_authenticated/cases/$id'
import { Route as AuthenticatedSettingsUsersIndexRouteImport } from './routes/_authenticated/settings/users/index'
import { Route as AuthenticatedSettingsRolesIndexRouteImport } from './routes/_authenticated/settings/roles/index'
import { Route as AuthenticatedSettingsInstitutionsIndexRouteImport } from './routes/_authenticated/settings/institutions/index'
import { Route as AuthenticatedSettingsInstitutionTypesIndexRouteImport } from './routes/_authenticated/settings/institution-types/index'
import { Route as AuthenticatedSettingsCircleRateUpliftIndexRouteImport } from './routes/_authenticated/settings/circle-rate-uplift/index'
import { Route as AuthenticatedSettingsBranchesIndexRouteImport } from './routes/_authenticated/settings/branches/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedValuationEstimatesIndexRoute =
  AuthenticatedValuationEstimatesIndexRouteImport.update({
    id: '/valuation-estimates/',
    path: '/valuation-estimates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedCasesIndexRoute = AuthenticatedCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesNewRoute = AuthenticatedCasesNewRouteImport.update({
  id: '/cases/new',
  path: '/cases/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesIdRoute = AuthenticatedCasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsUsersIndexRoute =
  AuthenticatedSettingsUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsRolesIndexRoute =
  AuthenticatedSettingsRolesIndexRouteImport.update({
    id: '/roles/',
    path: '/roles/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsInstitutionsIndexRoute =
  AuthenticatedSettingsInstitutionsIndexRouteImport.update({
    id: '/institutions/',
    path: '/institutions/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsInstitutionTypesIndexRoute =
  AuthenticatedSettingsInstitutionTypesIndexRouteImport.update({
    id: '/institution-types/',
    path: '/institution-types/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsCircleRateUpliftIndexRoute =
  AuthenticatedSettingsCircleRateUpliftIndexRouteImport.update({
    id: '/circle-rate-uplift/',
    path: '/circle-rate-uplift/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsBranchesIndexRoute =
  AuthenticatedSettingsBranchesIndexRouteImport.update({
    id: '/branches/',
    path: '/branches/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/cases/$id': typeof AuthenticatedCasesIdRoute
  '/cases/new': typeof AuthenticatedCasesNewRoute
  '/cases': typeof AuthenticatedCasesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/valuation-estimates': typeof AuthenticatedValuationEstimatesIndexRoute
  '/settings/branches': typeof AuthenticatedSettingsBranchesIndexRoute
  '/settings/circle-rate-uplift': typeof AuthenticatedSettingsCircleRateUpliftIndexRoute
  '/settings/institution-types': typeof AuthenticatedSettingsInstitutionTypesIndexRoute
  '/settings/institutions': typeof AuthenticatedSettingsInstitutionsIndexRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesIndexRoute
  '/settings/users': typeof AuthenticatedSettingsUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/cases/$id': typeof AuthenticatedCasesIdRoute
  '/cases/new': typeof AuthenticatedCasesNewRoute
  '/cases': typeof AuthenticatedCasesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/valuation-estimates': typeof AuthenticatedValuationEstimatesIndexRoute
  '/settings/branches': typeof AuthenticatedSettingsBranchesIndexRoute
  '/settings/circle-rate-uplift': typeof AuthenticatedSettingsCircleRateUpliftIndexRoute
  '/settings/institution-types': typeof AuthenticatedSettingsInstitutionTypesIndexRoute
  '/settings/institutions': typeof AuthenticatedSettingsInstitutionsIndexRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesIndexRoute
  '/settings/users': typeof AuthenticatedSettingsUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cases/$id': typeof AuthenticatedCasesIdRoute
  '/_authenticated/cases/new': typeof AuthenticatedCasesNewRoute
  '/_authenticated/cases/': typeof AuthenticatedCasesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/valuation-estimates/': typeof AuthenticatedValuationEstimatesIndexRoute
  '/_authenticated/settings/branches/': typeof AuthenticatedSettingsBranchesIndexRoute
  '/_authenticated/settings/circle-rate-uplift/': typeof AuthenticatedSettingsCircleRateUpliftIndexRoute
  '/_authenticated/settings/institution-types/': typeof AuthenticatedSettingsInstitutionTypesIndexRoute
  '/_authenticated/settings/institutions/': typeof AuthenticatedSettingsInstitutionsIndexRoute
  '/_authenticated/settings/roles/': typeof AuthenticatedSettingsRolesIndexRoute
  '/_authenticated/settings/users/': typeof AuthenticatedSettingsUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/settings'
    | '/'
    | '/cases/$id'
    | '/cases/new'
    | '/cases'
    | '/settings/'
    | '/valuation-estimates'
    | '/settings/branches'
    | '/settings/circle-rate-uplift'
    | '/settings/institution-types'
    | '/settings/institutions'
    | '/settings/roles'
    | '/settings/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/cases/$id'
    | '/cases/new'
    | '/cases'
    | '/settings'
    | '/valuation-estimates'
    | '/settings/branches'
    | '/settings/circle-rate-uplift'
    | '/settings/institution-types'
    | '/settings/institutions'
    | '/settings/roles'
    | '/settings/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/cases/$id'
    | '/_authenticated/cases/new'
    | '/_authenticated/cases/'
    | '/_authenticated/settings/'
    | '/_authenticated/valuation-estimates/'
    | '/_authenticated/settings/branches/'
    | '/_authenticated/settings/circle-rate-uplift/'
    | '/_authenticated/settings/institution-types/'
    | '/_authenticated/settings/institutions/'
    | '/_authenticated/settings/roles/'
    | '/_authenticated/settings/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/valuation-estimates/': {
      id: '/_authenticated/valuation-estimates/'
      path: '/valuation-estimates'
      fullPath: '/valuation-estimates'
      preLoaderRoute: typeof AuthenticatedValuationEstimatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/cases/': {
      id: '/_authenticated/cases/'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AuthenticatedCasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases/new': {
      id: '/_authenticated/cases/new'
      path: '/cases/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof AuthenticatedCasesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases/$id': {
      id: '/_authenticated/cases/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof AuthenticatedCasesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/users/': {
      id: '/_authenticated/settings/users/'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/roles/': {
      id: '/_authenticated/settings/roles/'
      path: '/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/institutions/': {
      id: '/_authenticated/settings/institutions/'
      path: '/institutions'
      fullPath: '/settings/institutions'
      preLoaderRoute: typeof AuthenticatedSettingsInstitutionsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/institution-types/': {
      id: '/_authenticated/settings/institution-types/'
      path: '/institution-types'
      fullPath: '/settings/institution-types'
      preLoaderRoute: typeof AuthenticatedSettingsInstitutionTypesIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/circle-rate-uplift/': {
      id: '/_authenticated/settings/circle-rate-uplift/'
      path: '/circle-rate-uplift'
      fullPath: '/settings/circle-rate-uplift'
      preLoaderRoute: typeof AuthenticatedSettingsCircleRateUpliftIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/branches/': {
      id: '/_authenticated/settings/branches/'
      path: '/branches'
      fullPath: '/settings/branches'
      preLoaderRoute: typeof AuthenticatedSettingsBranchesIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSettingsBranchesIndexRoute: typeof AuthenticatedSettingsBranchesIndexRoute
  AuthenticatedSettingsCircleRateUpliftIndexRoute: typeof AuthenticatedSettingsCircleRateUpliftIndexRoute
  AuthenticatedSettingsInstitutionTypesIndexRoute: typeof AuthenticatedSettingsInstitutionTypesIndexRoute
  AuthenticatedSettingsInstitutionsIndexRoute: typeof AuthenticatedSettingsInstitutionsIndexRoute
  AuthenticatedSettingsRolesIndexRoute: typeof AuthenticatedSettingsRolesIndexRoute
  AuthenticatedSettingsUsersIndexRoute: typeof AuthenticatedSettingsUsersIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
    AuthenticatedSettingsBranchesIndexRoute:
      AuthenticatedSettingsBranchesIndexRoute,
    AuthenticatedSettingsCircleRateUpliftIndexRoute:
      AuthenticatedSettingsCircleRateUpliftIndexRoute,
    AuthenticatedSettingsInstitutionTypesIndexRoute:
      AuthenticatedSettingsInstitutionTypesIndexRoute,
    AuthenticatedSettingsInstitutionsIndexRoute:
      AuthenticatedSettingsInstitutionsIndexRoute,
    AuthenticatedSettingsRolesIndexRoute: AuthenticatedSettingsRolesIndexRoute,
    AuthenticatedSettingsUsersIndexRoute: AuthenticatedSettingsUsersIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCasesIdRoute: typeof AuthenticatedCasesIdRoute
  AuthenticatedCasesNewRoute: typeof AuthenticatedCasesNewRoute
  AuthenticatedCasesIndexRoute: typeof AuthenticatedCasesIndexRoute
  AuthenticatedValuationEstimatesIndexRoute: typeof AuthenticatedValuationEstimatesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCasesIdRoute: AuthenticatedCasesIdRoute,
  AuthenticatedCasesNewRoute: AuthenticatedCasesNewRoute,
  AuthenticatedCasesIndexRoute: AuthenticatedCasesIndexRoute,
  AuthenticatedValuationEstimatesIndexRoute:
    AuthenticatedValuationEstimatesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
